build.linux.release:
	cargo build --release --target x86_64-unknown-linux-gnu

build.windows.release:
	cargo build --release --target x86_64-pc-windows-gnu

build.macos.release:
	cargo build --release --target x86_64-apple-darwin