/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProfileSchema {
  /**
   * The name of this profile
   */
  name: string;
  /**
   * The name of the profile to extend from. The profile inheritance happens on a control basis; if you have the control defined here it will not be resolved from the extended profile. Note: when saving the profile for sharing the fully resolved profile is saved without the extends fields to make sure profiles are independently shareable.
   */
  extends?: string;
  /**
   * Whether this profile supports auto-detection. Requires the supported controller USB ID and rail class information to be set
   */
  auto_select?: boolean;
  controls: {
    /**
     * The given name of this control (as calibrated)
     */
    name: string;
    assignments: (
      | (Momentary & ProfileAssignmentConditionsSchema)
      | (Toggle & ProfileAssignmentConditionsSchema)
      | (Linear & ProfileAssignmentConditionsSchema)
      | (DirectControl & ProfileAssignmentConditionsSchema)
      | (APIControl & ProfileAssignmentConditionsSchema)
      | (SyncControl & ProfileAssignmentConditionsSchema)
    )[];
    [k: string]: unknown;
  }[];
  controller?: {
    /**
     * The supported controller USB identifier (Vendor:Product)
     */
    usb_id?: string;
    /**
     * This is a copy of the SDL mapping. This can be embedded for portability
     */
    mapping?: {
      [k: string]: unknown;
    };
    /**
     * This is a copy of the controller calibration. This can be embedded for portability
     */
    calibration?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Defines the supported rail class names (can be found at the top of the cab debugger)
   */
  rail_class_information?: {
    class_name?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * The momentary switch assignment essentially just acts like a normal button
 */
export interface Momentary {
  type: "momentary";
  /**
   * The threshold which the gamepad control needs to exceed before triggering the action. For most momentary implementations this can be any value since most buttons report a value of 0 or 1
   */
  threshold: number;
  /**
   * Defines how to interpret the threshold. Defaults to exceeds where the action is executed when the value exceeds the threshold. Can also be set to equals for an exact comparison
   */
  match?: "exceeds" | "equals";
  /**
   * The actual action to activate when the threshold is exceeded
   */
  action_activate: KeysAction | DirectControlAction | APIControlAction | VirtualAction;
  /**
   * The action to activate when the threshold is not exceeded anymore. This defaults to just releasing the previously activated key(s).
   */
  action_deactivate?: KeysAction | DirectControlAction | APIControlAction | VirtualAction;
  [k: string]: unknown;
}
export interface KeysAction {
  /**
   * The keys to trigger (a list of key identifiers separated by +'s)
   */
  keys: string;
  /**
   * The number of seconds to hold the button down; can be omitted to just hold it until released
   */
  press_time?: number;
  /**
   * The minimum time in seconds to wait between keystrokes; can be omitted
   */
  wait_time?: number;
  [k: string]: unknown;
}
export interface DirectControlAction {
  /**
   * This is the direct control identifier which can be found using the Cab Debugger
   */
  controls: string;
  /**
   * The value to send to the cab. Acceptable values depend on the cab and can be determined by using the Cab Debugger
   */
  value: number;
  /**
   * The maximum rate at which this control can change
   */
  max_change_rate?: number;
  /**
   * Defines whether to use the value as a relative adjustment instead of an absolute one.
   */
  relative?: boolean;
  /**
   * Defines whether to hold the value by continuously sending the input value to the cab. This is only required for momentary levers which do not hold positions on their own in the game. (ie some independent brakes)
   */
  hold?: boolean;
  /**
   * Whether to use the normalized value instead of the non-normalized value
   */
  use_normalized?: boolean;
  /**
   * Enables showing the in-game notification when changing values
   */
  notify?: boolean;
  [k: string]: unknown;
}
export interface APIControlAction {
  /**
   * This is the direct api control identifier which can be found using the Cab Debugger (same as the direct control one). Does not support the {SIDE} placeholder.
   */
  controls: string;
  /**
   * The value to send to the cab. Acceptable values depend on the cab and can be determined by using the Cab Debugger
   */
  api_value: number;
  hold?: boolean;
  max_change_rate?: number;
  [k: string]: unknown;
}
/**
 * A virtual control action
 */
export interface VirtualAction {
  type: "virtual";
  /**
   * The name of the virtual control to update. Should start with 'virtual:' for clear segmentation
   */
  control: string;
  value: number;
  [k: string]: unknown;
}
export interface ProfileAssignmentConditionsSchema {
  /**
   * The conditions to apply to this assignment
   */
  conditions?: ProfileAssignmentConditionSchema[];
  /**
   * Defines the supported rail class names (can be found at the top of the cab debugger)
   */
  rail_class_information?: {
    class_name?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface ProfileAssignmentConditionSchema {
  /**
   * This is the control which needs to meet the condition
   */
  control: string;
  /**
   * The operation to apply to the control value (greater than, less than, ..)
   */
  operator: "gte" | "lte" | "gt" | "lt" | "eq";
  /**
   * The comparison value
   */
  value: number;
  [k: string]: unknown;
}
/**
 * The toggle assignment acts like a switch. Activating one action when pressed once, and activating another when pressed again.
 */
export interface Toggle {
  type: "toggle";
  /**
   * The threshold which the gamepad control needs to exceed before triggering the action. For most toggle implementations this can be any value since most buttons report a value of 0 or 1
   */
  threshold: number;
  /**
   * Defines how to interpret the threshold. Defaults to exceeds where the action is executed when the value exceeds the threshold. Can also be set to equals for an exact comparison
   */
  match?: "exceeds" | "equals";
  /**
   * The actual action to activate when toggling the first time
   */
  action_activate: KeysAction | DirectControlAction | APIControlAction | VirtualAction;
  /**
   * The action to execute when toggling the second time
   */
  action_deactivate: KeysAction | DirectControlAction | APIControlAction | VirtualAction;
  [k: string]: unknown;
}
/**
 * The linear assignment acts like a customized lever, triggering actions as values get exceeded at specific thresholds.
 */
export interface Linear {
  type: "linear";
  /**
   * The linear value which is considered neutral or idle - this can be used to map the lever value from 0-1 to -1 to 1
   */
  neutral?: number;
  thresholds: {
    /**
     * The threshold to exceed. When a neutral value is set; the value will exceed when below the -x.x value
     */
    value?: number;
    /**
     * When used in combination with value_step, can generate a set of thresholds between value and value_end by value_step to repeat the same action(s)
     */
    value_end?: number;
    /**
     * Only used in combination with value_end
     */
    value_step?: number;
    /**
     * The actual action to activate when the threshold is exceeded
     */
    action_activate?: KeysAction | DirectControlAction | APIControlAction | VirtualAction;
    /**
     * The action to execute when the lever goes below the threshold (optional)
     */
    action_deactivate?: KeysAction | DirectControlAction | APIControlAction | VirtualAction;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * The direct control assignment gives complete control over the cab levers by mapping the gamepad lever value directly onto the game
 */
export interface DirectControl {
  type: "direct_control";
  /**
   * The direct control name to control; can be identified using the Cab Debugger
   */
  controls: string;
  /**
   * Defines whether to hold the value by continuously sending the input value to the cab. This is only required for momentary levers which do not hold positions on their own in the game. (ie some independent brakes)
   */
  hold?: boolean;
  /**
   * Whether to use the normalized value instead of the non-normalized value
   */
  use_normalized?: boolean;
  /**
   * Enables showing the in-game notification when changing values
   */
  notify?: boolean;
  /**
   * The control range that will be remapped to 0,1 or 0,-1. This is useful when direct mapping partial ranges.
   */
  control_range?: {
    start: number;
    end: number;
    [k: string]: unknown;
  };
  input_value: DirectLikeInputValue;
  [k: string]: unknown;
}
/**
 * Defines the input value constraints of the direct like control
 */
export interface DirectLikeInputValue {
  /**
   * The minimum reachable value in the game cab; can be identified using the Cab Debugger
   */
  min: number;
  /**
   * The maximum reachable value in the game cab; can be identified using the Cab Debugger
   */
  max: number;
  /**
   * The maximum rate at which this control can change
   */
  max_change_rate?: number;
  /**
   * The step value to increase/decrease the values in (optional)
   */
  step?: number;
  /**
   * Acts similarly to step but allows for finer control and can be combined with null values to define free range zones. This is useful if you have a control which is partly notched and partly free
   */
  steps?: (null | number)[];
  /**
   * Whether to invert the input value before calculating the game value
   */
  invert?: boolean;
  step_thresholds?: StepThresholdDefinition[];
  [k: string]: unknown;
}
/**
 * Defines the threshold of a step which can be used to remap a direct/api control like value
 */
export interface StepThresholdDefinition {
  /**
   * Defines the actual threshold value
   */
  threshold: number;
  /**
   * Defines the threshold end value for ranges
   */
  threshold_end?: number;
  /**
   * Defines the tolerance for the threshold
   */
  threshold_tolerance?: number;
  [k: string]: unknown;
}
/**
 * The direct control assignment gives complete control over the cab levers by mapping the gamepad lever value directly onto the game's HTTP API. May introduce slight overhead compared to direct control
 */
export interface APIControl {
  type: "api_control";
  /**
   * The direct/api control name to control; can be identified using the Cab Debugger
   */
  controls: string;
  /**
   * The control range that will be remapped to 0,1 or 0,-1. This is useful when direct mapping partial ranges.
   */
  control_range?: {
    start: number;
    end: number;
    [k: string]: unknown;
  };
  hold?: boolean;
  input_value: DirectLikeInputValue;
  [k: string]: unknown;
}
/**
 * Sync control uses the value listener to increase the value up to the right value using keybinds
 */
export interface SyncControl {
  type: "sync_control";
  /**
   * The sync control identifier to control; can be identified using the Cab Debugger
   */
  identifier: string;
  /**
   * The control range that will be remapped to 0,1 or 0,-1. This is useful when direct mapping partial ranges.
   */
  control_range?: {
    start: number;
    end: number;
    [k: string]: unknown;
  };
  input_value: DirectLikeInputValue;
  action_increase: KeysAction;
  action_decrease: KeysAction;
  [k: string]: unknown;
}
